name: Java Maven Build, Publish & Deploy Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Verify build
        run: mvn --batch-mode --update-snapshots verify
      - name: Prepare artifact
        run: mkdir staging && cp target/*.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
          retention-days: 90

  deploy-job:
    runs-on: ubuntu-latest
    needs: publish-job
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Package
          path: staging

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy with Maven
        run: mvn deploy --settings ~/.m2/settings.xml
